server.port: 9000
spring:
  application.name: authentication

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: pgpass

  mvc:
    log-request-details: true
logging:
  level:
    root: INFO
    fr.f4fez: INFO

qsp.authorization:
  clients:
    portal:
      redirect-uri:
        - "http://localhost:3000/src/assets/login-redirect.html"
      access-token-time-to-live: 3
      refresh-token-time-to-live: 720